### ISSUE TITLE
Quiz is broken in perception / prediction interaction section

### ISSUE THREAD

**Issue by schrezraoeder** [udacity/sdc-issue-reports#1007] opened 2017-08-20 16:36 UTC

**Comment by schrezraoeder** [comment] 2017-08-20 16:37
Question 1 of 2 will apparently accept just about any answer. I.e., mark it as correct. It gives the same feedback regardless of what selection the user makes. It is clear from the feedback what the correct answer is, but, it could possibly still throw some users off, especially depending on how tired they are when looking at the materials, etc. Either way, it's an error. https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/b0b462f1-6656-42c9-8fdb-3c99b733658e/concepts/8bb13675-7a2e-4a73-9f25-bda2a4b3eb47

**Comment by schrezraoeder** [comment] 2017-08-20 16:41
Oh, Term 3.

**Comment by baumanab** [comment] 2017-08-21 01:02
Thanks for giving us feedback on this.  The quiz is actually working as intended since all the answers are correct.  As the response indicates some are more correct than others.  Is there something specific you think we could change to make this more clear?

**Comment by baumanab** [comment] 2017-08-26 05:50
Closed as not actionable without updated information.

**Closed by baumanab** 2017-08-26 05:50 UTC
Labels: in progress
