### ISSUE TITLE
Severe communication issues in Simulator Term 3

### ISSUE THREAD

**Issue by ricgu8086** [udacity/sdc-issue-reports#1049] opened 2017-09-06 18:55 UTC
When launching Term3-P1-path-planning project with the code provided in the lessons just to make a straight line, the program is able to connect to the simulator and send the info, however, the simulator does not do anything with it and the car does not move. The same code in a different machine works.

The code used
https://github.com/ricgu8086/CarND-Path-Planning-Project/commit/2d253bf64e94dad9e286374be477a66f5e8fa5bd

and more info:
https://discussions.udacity.com/t/the-car-does-not-move-in-the-simulator-using-the-getting-started-code/353517

**Comment by baumanab** [comment] 2017-09-06 21:17
Thanks for reporting this.  It sounds like the code works on one system and not on the other. Is that correct?  What are the differences between the two systems?

**Comment by ricgu8086** [comment] 2017-09-08 18:13
Exactly. The first system is Ubuntu 16.04. Seems to work (displays the Connected!!! message) but somehow doesn't send the correct message, as the car is not moving. The second system is complicated, it's a Windows 7 machine that has a virtual machine with Ubuntu 16.04. As the simulator is not able to run on the virtual machine (after pressing accept in the graphics dialogue at the very beginning the simulator unexpectedly close without any further message) I am running the simulator in the Windows machine and my code in the virtual machine.

In the virtual machine (second system) I don't really know which problem is, but in the first system I would bet on libuWS. If you have any test code or something I can give it a try. Or if you need something else, I would like to help.

**Comment by baumanab** [comment] 2017-09-18 04:40
Sorry for the delay. I'm confused. From the forum post it sounds like everything worked on one system, but here it sounds things didn't work on either system. Would you mind clarifying?  It may be worth reinstalling the project as well as dependencies.

**Comment by JeffersonH44** [comment] 2017-09-18 09:47
I have the same problem, using ubuntu 16.06 and Debian 8, I don't know how to solve that issue, I used the exact code as @ricgu8086

**Comment by ducktrA** [comment] 2017-09-20 21:10
Hi,
i experience the same issues on two Ubuntu 16.04 boxes. It seems to me that the h.onMessage handler is called exactly twice when the simulator is started from scratch. In the first run it receives a json package it can work with. After sending off the response to the sim, the h.onMessage receives a "stupid" json the next time ending in a segfault. 

i printed the received data h.onMessage gets and the data in the second json seem completely nonsense.

42["telemetry",{"x":909,"x":48,"y":1128,"y":67,"yaw":0,"speed":0,"s":124,"s":8336,"d":6,"d":164833,"previous_path_x":[],"previous_path_y":[],"end_path_s":0,"end_path_d":0,"sensor_fusion":[[0,775,99,1421,6,0,0,6721,839,-277,6729],[1,775,8,1425,2,0,0,6719,219,-280,1494],[2,775,8,1429,0,0,6716,599,-282,9019],[3,775,8,1432,9,0,0,6713,911,-285,7268],[4,775,8,1436,3,0,0,6711,566,-288,1896],[5,775,8,1441,7,0,0,6661,772,-291,7797],[6,762,1,1421,6,0,0,6711,778,-268,964],[7,762,1,1425,2,0,0,6709,296,-270,7039],[8,762,1,1429,0,0,6663,543,-273,1828],[9,762,1,1432,9,0,0,6660,444,-275,5511],[10,762,1,1436,3,0,0,6657,743,-277,6157],[11,762,1,1441,7,0,0,6653,453,-280,8947]]}]
2

42["telemetry",{"x":-2,"x":2,65322E+19,"y":-1,"y":6,36751E+19,"yaw":215,"yaw":8849,"speed":3,"speed":1,25841E+21,"s":2,"s":2,20424E+19,"d":1,"d":6,97161E+19,"previous_path_x":[-2,2,64823E+19,-2,2,64323E+19,-2,2,63823E+19,-2,2,63323E+19,-2,2,62823E+19,-2,2,62324E+19,-2,2,61824E+19,-2,2,61324E+19,-2,2,60824E+19,-2,2,60324E+19,-2,2,59825E+19,-2,2,59325E+19,-2,2,58825E+19,-2,2,58325E+19,-2,2,57825E+19,-2,2,57325E+19,-2,2,56826E+19,-2,2,56326E+19,-2,2,55826E+19,-2,2,55326E+19,-2,2,54826E+19,-2,2,54326E+19,-2,2,53827E+19,-2,2,53327E+19,-2,2,52827E+19,-2,2,52327E+19,-2,2,51827E+19,-2,2,51328E+19,-2,2,50828E+19,-2,2,50328E+19,-2,2,49828E+19,-2,2,49328E+19,-2,2,48828E+19,-2,2,48329E+19,-2,2,47829E+19,-2,2,47329E+19,-2,2,46829E+19,-2,2,46329E+19,-2,2,4583E+18,-2,2,4533E+18,-2,2,4483E+18,-2,2,4433E+18,-2,2,4383E+18,-2,2,43331E+19,-2,2,42831E+19,-2,2,42331E+19,-2,2,41831E+19,-2,2,41331E+19,-2,2,40831E+19],"previous_path_y":[-1,6,36751E+19,-1,6,36751E+19,-1,6,36751E+19,-1,6,36751E+19,-1,6,36751E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36752E+19,-1,6,36753E+19,-1,6,36753E+19,-1,6,36753E+19,-1,6,36753E+19,-1,6,36753E+19,-1,6,36753E+19,-1,6,36753E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36754E+19,-1,6,36755E+19,-1,6,36755E+19,-1,6,36755E+19,-1,6,36755E+19,-1,6,36755E+19,-1,6,36755E+19,-1,6,36755E+19,-1,6,36756E+19,-1,6,36756E+19,-1,6,36756E+19,-1,6,36756E+19,-1,6,36756E+19,-1,6,36756E+19,-1,6,36757E+19,-1,6,36757E+19,-1,6,36757E+19,-1,6,36757E+18,-1,6,36757E+18,-1,6,36757E+18,-1,6,36757E+17,-1,6,36757E+18],"end_path_s":2,"end_path_s":2,35611E+19,"end_path_d":2,"end_path_d":2,39599E+18,"sensor_fusion":[[0,815,6177,1128,926,23,46231,0,2555184,31,283,6,3918],[1,775,8,1425,2,0,0,6719,219,-280,1494],[2,775,8,1429,0,0,6716,599,-282,9019],[3,775,8,1432,9,0,0,6713,911,-285,7268],[4,775,8,1436,3,0,0,6711,566,-288,1896],[5,775,8,1441,7,0,0,6661,772,-291,7797],[6,762,1,1421,6,0,0,6711,778,-268,964],[7,762,1,1425,2,0,0,6709,296,-270,7039],[8,762,1,1429,0,0,6663,543,-273,1828],[9,762,1,1432,9,0,0,6660,444,-275,5511],[10,762,1,1436,3,0,0,6657,743,-277,6157],[11,762,1,1441,7,0,0,6653,453,-280,8947]]}]

**Comment by ducktrA** [comment] 2017-09-21 06:29
Hi again,

i updated uWS to latest master. I have exactly the same behaviour. That makes me believe that the problem is elsewhere.

Has the simulator  a way to output debug messages? 

Best

**Comment by ducktrA** [comment] 2017-09-22 11:52
Hi again,

i got it running on a different system. Let me do the project and i dig in deeper. The platform which it runs now is a system which was installed an old system ( i guess installed as ubuntu 14 and updated to ubuntu 16.02).

I think the problem can be reproducede using a brand new Ubuntu 16.04 install. both of the systems i have trouble with got this. 

Best.

**Comment by baumanab** [comment] 2017-09-22 18:19
Please let us know how this progresses.  If it helps, I am running Ubuntu Bash 16.04 on Win 10.

**Comment by baumanab** [comment] 2017-10-13 04:14
Closed as not actionable without further information.

**Closed by baumanab** 2017-10-13 04:14 UTC
Labels: in progress, JIRA, np, simulator
