### ISSUE TITLE
Term 3 Preditcion.I/O Recap missing vehicle for ID=1

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#897] opened 2017-07-09 15:29 UTC
There is no vehicle with ID=1 in the json file. Only 2 predictions for ID=0 and another prediction for ID=0. So the correct answer of the quiz would be 3+

**Comment by anupriyachhabra** [comment] 2017-07-12 06:29
I see the same issue

**Comment by ksmith6** [comment] 2017-07-12 14:38
Duplicate of 895

**Comment by baumanab** [comment] 2017-07-22 23:06
Thank you for report this, the issue has been addressed.

**Closed by baumanab** 2017-07-22 23:06 UTC
Labels: ready
