### ISSUE TITLE
VM Image for System Integration - Blank Screen

### ISSUE THREAD

**Issue by dehavenm** [udacity/sdc-issue-reports#1112] opened 2017-09-16 22:26 UTC
I've downloaded the VM disk image from this link, as instructed:

https://s3-us-west-1.amazonaws.com/udacity-selfdrivingcar/Udacity_VM_Base_V1.0.0.zip

It worked properly for a while, but now whenever I start ot, it gets to the login screen, I enter the passwork, and then the screen goes blank. I've tried restarting it multiple times, as well as my computer, but it's still not working. I've checked all the settings in Virtualbox, and everything appears to be where it should be.

**Comment by swwelch** [comment] 2017-09-18 16:31
Hi @dehavenm,

This sounds like a Linux issue, usually caused by an update not installing completely. Can you check here to see if that fixes your [problems](https://seravo.fi/2015/fixing-black-screen-after-login-in-ubuntu-14-04)?

**Comment by baumanab** [comment] 2017-09-25 04:19
Closed as not actionable without updated information.

**Closed by baumanab** 2017-09-25 04:19 UTC
Labels: in progress
