### ISSUE TITLE
T2L.11.p6 Markov localization

### ISSUE THREAD

**Issue by babo** [udacity/sdc-issue-reports#781] opened 2017-05-07 14:27 UTC
The expected code should print observations but there are no observations in the test dataset. Any code which compiles passes the filter. The task asks to print the first four values while the solution prints all.

I expect some observation value to test, a better description of the expected output, and a downloadable sample to try locally.

**Comment by baumanab** [comment] 2017-07-25 06:23
Thank you for the feedback.  We are looking into this.  This may be a possible duplicate of #778 and #879.

**Comment by baumanab** [comment] 2017-08-23 06:41
The data package for running this code locally is now available for download in the resources tab.

**Comment by baumanab** [comment] 2017-09-06 15:02
Closing as duplicate. #778 remains open.

**Closed by baumanab** 2017-09-06 15:02 UTC
Labels: code, duplicate, effort-Medium, enhancement, term_2
