### ISSUE TITLE
term 3 simulator log grows forever

### ISSUE THREAD

**Issue by Goddard** [udacity/sdc-issue-reports#1211] opened 2017-11-08 01:02 UTC
The logs for the simulator grows forever so if a student leaves it open it will destroy their operating system and cause a lot of problems and may be difficult to fix some of them.  Cap the log file to a reasonable size.

**Comment by baumanab** [comment] 2017-11-08 03:47
Wow, thanks for letting us know. I will alert the simulator team.

**Comment by baumanab** [comment] 2017-11-08 04:02
I was actually able to speak to the main developer.  This is hopefully something that will be addressed in an upcoming release.  It is actually something that can be modified by linux and possibly mac users.  In any case I'm going to put a warning in the classroom until the issue is resolved.

**Comment by baumanab** [comment] 2017-11-17 20:00
related to #994

**Comment by baumanab** [comment] 2017-11-17 20:35
Notes were added to the EKF repo and project page.  This is the first place the simulator is encountered.  A document containing information about this as well as workarounds has been added to the release page.  We have opened an internal ticket, so I'm closing this out.

https://udacity.atlassian.net/browse/DRIVE-4384

**Closed by baumanab** 2017-11-17 20:35 UTC
Labels: in progress, JIRA, simulator
