### ISSUE TITLE
Term3, Lesson5, Section 21 Mistakes Derivation in Derivation of Coefficients

### ISSUE THREAD

**Issue by jendrikjoe** [udacity/sdc-issue-reports#930] opened 2017-07-19 08:29 UTC
https://discussions.udacity.com/t/lesson-5-21-one-coefficient-wrong/311879

**Comment by baumanab** [comment] 2017-07-25 17:35
Thank you for reporting this.  It looks like this is a duplicate of #923

**Comment by jendrikjoe** [comment] 2017-07-25 18:13
Hello Andrew,

the mistake I detected is later in the video, than the one from #923.

Cheers,

Jendrik

On 25. Jul 2017, at 19:37, Andrew Bauman <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for reporting this. It looks like this is a duplicate of #923<https://github.com/udacity/sdc-issue-reports/issues/923>

**Comment by baumanab** [comment] 2017-11-21 04:27
Thank you for reporting this.  This has been corrected.

**Closed by baumanab** 2017-11-21 04:27 UTC
Labels: duplicate, effort-High, term_1, vid-maintenance, work-around
