### ISSUE TITLE
Incorrect value in SDCN T2, L7, S13?

### ISSUE THREAD

**Issue by KenOverholt** [udacity/sdc-issue-reports#973] opened 2017-07-29 16:06 UTC
Term x sub k in the video of Term 2 Lesson 7, section 13 seems to be incorrect.

**Comment by KenOverholt** [comment] 2017-07-29 16:10
I can't get a picture to upload here so I'll just post the link to the forms where I described the issue: https://discussions.udacity.com/t/incorrect-value-in-lesson-7-section-13/323573.

**Comment by mvirgo** [comment] 2018-08-27 21:46
Duplicate of #776

**Closed by mvirgo** 2018-08-27 21:46 UTC
Labels: JIRA, in_Jira, term_2, vid-maintenance
