### ISSUE TITLE
Link for windows make goes to 3.81

### ISSUE THREAD

**Issue by pcarney8** [udacity/sdc-issue-reports#836] opened 2017-06-01 00:40 UTC
In CarND-PID-Control-Project and i believe all the other Term 2 projects that use C++ this block:

make >= 4.1
Linux: make is installed by default on most Linux distros
Mac: install Xcode command line tools to get make
Windows: Click here for installation instructions

links to a window 3.81 version of make even though stating we need make >= 4.1

**Comment by baumanab** [comment] 2017-07-25 07:11
duplicate of #728

**Comment by baumanab** [comment] 2017-08-22 04:23
Thanks for pointing this out.  A note has been added to the resource pages and the github repositories for EKF and UKF projects.

**Closed by baumanab** 2017-08-22 04:23 UTC
Labels: duplicate, effort-Low, in progress, Project-maintenance, term_2
