### ISSUE TITLE
Ipopt Windows Installation Issue

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1209] opened 2017-11-06 09:47 UTC
One student [pointed out](https://discussions.udacity.com/t/mpc-build-issue/287473/33?u=subodh.malgonde) that having a space in the home folder name causes problems during installation of IPOPT, when using Ubuntu bash on Windows. Installing a new folder, with no space in the name, works.

It would be great if we could add a fix or a warning in the classroom about this.

**Comment by baumanab** [comment] 2017-11-06 15:04
That is really interesting. Yes, a space would be interpreted as the end of a folder/filenane. Out of curiosity, how does one end up with a space in the home folder?

**Comment by baumanab** [comment] 2017-11-06 15:25
Never mind, I see how it happened.

**Comment by baumanab** [comment] 2017-11-06 19:00
Would you mind fielding some follow up questions to help me devise the best solution?  

It looks like the root of the issue is that students are passing a windows path to the install script, and when any element of that path contains a space, the install fails.  Is that correct?  We could put in a warning or suggest that the path is passed as a string literal.  However, my thought is that as a best practice users should place the install script in the Ubuntu BASH instance and install from there.  If users follow the install instructions this will happen naturally, via wget.  What do you think?

**Comment by subodh-malgonde** [comment] 2017-11-07 05:24
I don't think students are passing a Windows path to the installation script. They are doing it as per instructions. If you look at the [screenshot in this post](https://discussions.udacity.com/t/mpc-build-issue/287473/17?u=subodh.malgonde), you will notice that the problem occurs when the script tries to configure ASL.

**Comment by baumanab** [comment] 2017-11-07 06:18
Thanks for following up.  My apologies if I am missing something but it does look like Ipopt-3.12.7 was placed in a Windows directory and that the path given to the script is a path to that directory.   That directory happens to have a space (in the username).  /mnt/c is the path from Ubuntu Bash to Windows.  This is the path to ASL relative to Ipopt-3.12.7.   

```
Ipopt-3.12.7/ThirdParty/ASL
```
The prefix to that path in the screenshot is to a Windows directory containing that Ipopt-3.12.7.  When I have tested the instructions on Linux as well as Ubuntu Bash Ipopt-3.12.7 ends up in the same folder as the install script (via wget).  So, the error the student is experiencing does not seem possible if the instructions are followed.  Am I missing something? Please let me know if that is the case.

**Comment by subodh-malgonde** [comment] 2017-11-07 10:20
This was the comment by that student:

> This is the last error message I get after using:
sudo bash install_ipopt.sh Ipopt-3.12.7

So it does look like that the student has followed the instructions. I have requested him to confirm.

**Comment by baumanab** [comment] 2017-11-07 14:47
Thanks for following up with the student. If the instructions are being followed there may be some other elements to address in terms of what the script is doing.

**Comment by baumanab** [comment] 2017-11-07 19:32
Here is what this looks like on my system, the entire path in Ubuntu Bash:

```
make[1]: Entering directory '/root/control_maintenance/quizzes/Ipopt-3.12.7/ThirdParty/ASL'
```

**Comment by subodh-malgonde** [comment] 2017-11-08 06:09
Ok. So I think the problem arises when the entire path contains a space.

Eg.

> Entering directory '/mnt/c/Users/Siddharth Singi/SDCND/Term-2/Files-Simulator/Ipopt-3.12.7/ThirdParty/ASL

But the compile command takes only some part of the path:

> ./compile_Unix_ASL: 16 ./compile_Unix_ASL: Singi/SDCND/Term-2/Files_Simulator/Ipopt-3.12.7/ThirdParty/ASL: not found

**Comment by baumanab** [comment] 2017-11-08 06:19
Yes, in linux environments a space will be interpreted as a break unless the space is escaped with ```\``` or the path is entered as string literal ```"<path>"```  This is a common linux pitfall.  What I'm wondering is how a windows path became the path containing the ipopt file.  This is the type of path one would use to access a file on the windows system.  Occasionally I copy from host to Ubuntu and the first part of that process is ```cd /mnt/c```.  If this is somehow occurring in the absence of the student setting or otherwise setting that path, then there may be something odd going on with the script.

**Comment by SiddharthSingi** [comment] 2017-11-08 14:18
Hello, I was facing these issues while installing in Ubuntu Bash 16.04 on windows 10. Here is a list of the complete instructions I used:

`cd /mnt/c/Users/"Siddharth Singi"/SDCND/Term-2/CarND-MPC-Quizzes`
`sudo apt-get install gfortran`
`sudo apt-get install unzip`
`wget https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.7.zip && unzip Ipopt-3.12.7.zip && rm Ipopt-3.12.7.zip`

Then I used `sudo bash ./install_ipopt.sh Ipopt-3.12.7` (I also tried with just sudo or just bash). 
This line, however, gave me a lot of errors because of the space in the folder name. This arose due to a line in install_ipopt.sh : `srcdir=$PWD` . The problem is that after this if you were to use `cd srcdir` Bash cannot figure out space in the folder name, so to overcome this I edited install_ipopt.sh a little. This was the install_ipopt.sh file that I edited:

```
# Pass the Ipopt source directory as the first argument
if [ -z $1 ]
then
    echo "Specifiy the location of the Ipopt source directory in the first argument."
    exit
fi
cd $1

prefix=/usr/local
echo prefix
echo local
# srcdir=$PWD
srcdir="/mnt/c/Users/Siddharth Singi/SDCND/Term-2/CarND-MPC-Quizzes/Ipopt-3.12.7"

echo "Building Ipopt from ${srcdir}"
echo "Saving headers and libraries to ${prefix}"

# BLAS
cd "$srcdir/ThirdParty/Blas"
./get.Blas
mkdir -p build && cd build
../configure --prefix=$prefix --disable-shared --with-pic
make install
echo "Blas Successful"

# Lapack
cd "$srcdir/ThirdParty/Lapack"
./get.Lapack
mkdir -p build && cd build
../configure --prefix=$prefix --disable-shared --with-pic \
    --with-blas="$prefix/lib/libcoinblas.a -lgfortran"
make install
echo "Lapack Successful"

# ASL
cd "$srcdir/ThirdParty/ASL"
./get.ASL
echo "ASL Successful"

# MUMPS
cd "$srcdir/ThirdParty/Mumps"
./get.Mumps
echo "MUMPS Successful"

# build everything
cd "$srcdir"
./configure --prefix=$prefix coin_skip_warn_cxxflags=yes \
    --with-blas="$prefix/lib/libcoinblas.a -lgfortran" \
    --with-lapack=$prefix/lib/libcoinlapack.a
make
make test
make -j1 install
```

I have basically added double quotes in all the change directory commands and used a different srcdir string. These edits worked till installation of MUMPS without errors, but when it came to `./configure --prefix=$prefix coin_skip_warn_cxxflags=yes \` , I started getting problems in prefix.

Now I don't really have any idea about Linux so I tried my best to get it to work so far but after this, I just got fed up and started an entirely new project in a folder which did not have any spaces in its path. However, subodh pointed out that to get the prefix to work I can also try using something like this https://discussions.udacity.com/t/mpc-build-issue/287473/32.

Best of Luck in fixing the issue.
Regards
Siddharth Singi

**Comment by baumanab** [comment] 2017-11-08 18:05
Hi Siddharth,

Thank you for posting this, it is really helpful and cleared up my misunderstanding.  It's clear to me that there is one element of the instructions that require clarification.  The intent was for the instructions to be executed in the repo folder, in Ubuntu Bash.  If you leave out the first step, the CD to the Windows host system, everything should work.  Alternatively you could escape the space, but it's a good practice to stay in the Ubuntu BASH environment unless there is a compelling reason to do otherwise (transferring a file for example).  I've actually written an install script which automates dependencies installs for these quizzes.  I think I'll bring that in now as well as clarify the instructions.  This was really helpful, thanks to to both of you for finding a bug to squash :).

**Comment by baumanab** [comment] 2017-11-08 19:37
I've updated the instructions and also added a script to the quizzes repo that will install all dependencies.

**Closed by baumanab** 2017-11-08 19:37 UTC
Labels: in progress
