### ISSUE TITLE
Term 3, lesson 3.2

### ISSUE THREAD

**Issue by olegleyz** [udacity/sdc-issue-reports#904] opened 2017-07-12 11:52 UTC
in the example json, in prediction for the second car (id = 1) id should be changed from 0 to 1.

**Comment by ksmith6** [comment] 2017-07-12 14:38
This appears to be a duplicate of 897.

**Comment by baumanab** [comment] 2017-07-22 23:44
Thanks for reporting this.  This issue has now been addressed.

**Closed by baumanab** 2017-07-22 23:44 UTC
Labels: ready
