### ISSUE TITLE
Term 2, Lesson 5.21, 5.22, 5.23 grader is very confusing

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1166] opened 2017-10-18 16:30 UTC
It looks like the "submit answer" button on lesson 5 parts 21, 22, 23 (the Coding II quizzes) is always expected to fail. Is that correct?

It's very non-obvious that the quizzes expect a partial solution (as we're supposed to build in each part in subsequent quizzes), but the grader appears to reject anything but a full solution.

But the grader also appears to reject the full solution: when I copy the full code from 5.24 "Coding II: Explanation of Code" (the provided complete solution), which passes the 5.24 grader, into the 5.23 quiz and submit, I see a prompt that says "Try again" in red text with an error that says "Thank you for your submission!"

Similarly, if I paste the solution code from 5.24 into 5.22, the submission passes *but 5.22 does not ask for or expect full solution code*. The actual requested solution for 5.22 does not include the motion model, and should generate a different answer.

The grader rejecting correct partial solutions, and only (sometimes) accepting full solutions to the *following* quizzes, is very confusing. Can we at the very least document this in large text in the quiz instructions, or better yet fix the grader to accept the partial answers requested in each quiz?

**Comment by baumanab** [comment] 2017-10-18 17:15
Hi!  Thank you for posting this.  We are actually actively working on improving the experience for these quizzes.  Until recently these quizzes were all one step, with no intermediate steps.  We broke the quizzes the up in an attempt to make them more manageable.  We are also thinking of porting them to a lab or workspace to give students a little more freedom to play with the code and data.  That being said, there is clearly still some understandable confusion.  I'm going to respond to your post inline.  Feedback on my responses would be very helpful.  I'm also happy to pick this back up in a slack or hangout conversation.   Posting inline responses in the next comment.

**Comment by baumanab** [comment] 2017-10-18 17:30
> It looks like the "submit answer" button on lesson 5 parts 21, 22, 23 (the Coding II quizzes) is always expected to fail. Is that correct?

Yes, this will fail.  This exercise is not really conducive to grading intermediate steps.  There may be some unit tests or assertions that can be added to help guide students.  I think this will be less critical if we port the quiz to a lab or workspace as students will be able to investigate more.  Currently, we have the data available for download.  I'm working on getting the starter code and quiz solutions available for download as well.  This way students can run the quiz locally.  **Will that be helpful?**

> It's very non-obvious that the quizzes expect a partial solution (as we're supposed to build in each part in subsequent quizzes), but the grader appears to reject anything but a full solution.

Sorry that this wasn't clear.  The following is posted prior to the quiz. 

> Your main task for this quiz is to modify the code in bayesianFilter.cpp and bayesianFilter.h to output the correct believe state after moving 14 steps to the right. This coding exercise is comprised of 3 main tasks. The grader can be used to evaluate after all 3 tasks are complete.

I can see where this information may not stand out.  **What can we do to make this clear?**

> But the grader also appears to reject the full solution: when I copy the full code from 5.24 "Coding II: Explanation of Code" (the provided complete solution), which passes the 5.24 grader, into the 5.23 quiz and submit, I see a prompt that says "Try again" in red text with an error that says "Thank you for your submission!"

This was working prior to release.  I just tested it and it is still working.  The key is that you have to paste in the code from the bayesian_Filter.h and bayesian_Filter.cpp for everything to work.

> Similarly, if I paste the solution code from 5.24 into 5.22, the submission passes but 5.22 does not ask for or expect full solution code. The actual requested solution for 5.22 does not include the motion model, and should generate a different answer.

> The grader rejecting correct partial solutions, and only (sometimes) accepting full solutions to the following quizzes, is very confusing. 

The breakdown of the quiz was intended to break up the instructions and solution into pieces to make the content more manageable.  This way a portion can be completed and that portion can be checked against the instructor solution.

> Can we at the very least document this in large text in the quiz instructions, or better yet fix the grader to accept the partial answers requested in each quiz? 

We can definitely enhance the instructions and make this element more obvious.  Ultimately we can address the second part of this request.  How we address that will be dependent on the form these quizzes ultimately take.  

**Please let us know what you think, given this updated information.**

**Comment by baumanab** [comment] 2017-10-18 17:39
As an update, I've made some changes to clarify that the grader evaluates all tasks rather than intermediate tasks.

**Comment by CodingCanuck** [comment] 2017-10-18 18:04
One minor improvement would be to replace:
"The grader can be used to evaluate after all 3 tasks are complete."

With:
"Note that the submit button will reject a successful answer to the first 2 parts of the quiz: it will only accept the third quiz's answer".

But this is really just papering over a poor student experience: this was the most confusing lesson structure I've included in the nanodegree so far. The split between quizzes is under-defined and perhaps not well thought out. For example it's not clear what bel_x_init's type is supposed to be in quiz 1 because you don't see how it's used. When the ground truth is displayed in quiz 1 and 2 it leads the student to believe their implementation is wrong. The first two quizzes have both too much information and not enough: the first quiz contains a "posterior_motion" variable that is never used or explained, and the instructions in quiz 1 say "this coding exercise [which seems to refer to the current partial quiz] is comprised of 3 main tasks." then it lists tasks which are actually not supposed to be implemented in future quizzes.

I'd recommend you rethink this new quiz structure. Quizzes or other exercises are most educational and useful when they're self-contained: hinting at information in future lessons (but not fully explaining it) is not useful and adds confusion. Either make the split between crisper (such that the grader accepts answers for each quiz, and quizzes don't have code references to future material), or merge the quizzes back into one (so full context is in one place, and you can submit a gradable complete piece of work).

I think a merged quiz or lab is the best approach here that will be easiest for students to digest. Something like a skeleton with with ~similar versions of the comments from all three quizzes, but those comments should probably be updated to give rough guidance instead of literal partial code samples.

**Comment by CodingCanuck** [comment] 2017-10-19 15:38
I'm sure you're aware, but the same issue exists with lesson 7.29: Coding III: Implementation with One and Multiple Observation.

A successful/correct solution to the quiz in 7.29 gives a submission error of "Try Again It looks like bel_x=0: is incorrect Try checking your work and resubmitting". Testing a valid result for the first quiz prints out nan's for each point:
bel_x=0:	-nan	ground truth:	0.00000

because the quiz code initializes bel_x to all zeros then normalizes the vector, generating nans (where each element = 0 / 0).

This looks like a similar quiz which was recently split: a slight improvement would be to make it very clear that submission and testing results won't tell you if your answer is correct, the only way to grade your own answer is to open the next quiz 7.30 and visually compare your code to the solution. A better improvement would be to combine these into a single quiz again, or to make each partial quiz "standalone" such that a correct answer can be tested and submitted successfully.

**Comment by baumanab** [comment] 2017-10-20 22:59
Thanks again for your feedback.  As a start the classroom now contains starter code and solution code for all 3 quizzes, along with the data package.  Would you mind taking a look and letting us know if this is helpful?

**Comment by CodingCanuck** [comment] 2017-10-22 19:50
I'm sorry, I must've reported the wrong lesson titles in my previous comments :/ I was referring to the coding quizzes under term 2's lesson 11 (Markov Localization), I'm not sure where I got lessons 5 or 7 from.

Which classrooms/quizzes were updated? I just tried resetting the quiz for 11.21 ("Coding II: Implement the Motion Model Part 1"), and 1) I didn't see any changes to the starter code (but I don't remember what it used to look like 2) the test run button still prints out ground truth that don't match the output of a correct answer for the first quiz 3) the grader still rejects a correct answer for the first quiz (because it expects the full answer from the fourth part/solution of this multi-part quiz)

**Comment by baumanab** [comment] 2017-10-23 03:46
Sorry for any confusion.  I actually knew which quizzes you meant and checked on those.  If you enter the full solution into any of the quizzes the grader will show as correct.  Only the full answer will be accepted by the grader, per our earlier conversation.  The quizzes have not been updated since our last communication, but the portion of instructions that lets' people know about intermediate answers not being accepted by the grader was highlighted.  We are actively working on improving the experience for these quizzes and I will update here when changes are made.  In the meantime I have uploaded all the quiz starter code, data, solution code, and scripts (.sh) into resources.  So, this will allow the code to be run and one entity and allows debugging etc.  Would you mind trying it out and letting us know what you think?  To run:

- unpack .zip
- cd to unzipped dir
- execute ./build.sh
- execute ./run.sh

**Comment by CodingCanuck** [comment] 2017-10-23 04:27
Do you mean this sentence was made large and bold? "Tasks: This coding exercise is comprised of 3 main tasks. The grader can be used to evaluate after all 3 tasks are complete."

If I rewrite this sentence in code, it says:
if (AllTasksComplete()) {
  GraderMayBeUsed();
} else {
  // Undefined by instructions, not clear that grader rejects answers for the partial quizzes
}

To fix that and better document the current behavior, how about rephrasing that sentence to be:
Tasks: This coding exercise is comprised of 3 main tasks, split into three quizzes. Each quiz builds on work from the previous quiz. The grader can only be used to evaluate the final quiz after all 3 tasks are complete: the grader won't accept any answers from the first quizzes (since your test output won't match the ground truth until you've completed all of the quizzes).


The quiz page (for 11.21) currently doesn't mention that the code is available in resources, so it's currently not obvious that one should look there. I assume that's by design while we're iterating on this :)

Having the solutions explicitly available definitely helps by giving students a way to check what's expected: I seem to remember earlier quizzes (maybe in term 1) having a "show solution" button or tab on similar coding quizzes.

I think the core thing though is that having a "submit" button that rejects correct answers is just confusing. I think you're thinking of some smart workarounds for that, but workarounds won't fix the core issue.

There are other quizzes with submit answer buttons that say something like "this quiz isn't graded: please check your own output!", that would be a big improvement if we can't correctly grade answers right now.

The other thing that would help would be to clarify what a correct solution looks like (this is normally what a grader would do, but let's work with the assumption that we can't get the grader fixed for a while). Another nice option would be to give correct sample output for each quiz: right now the test run output implies that the quiz output should match the ground truth, which it shouldn't until the last quiz: maybe remove the ground truth from the first two quizzes, and have something like "sample map value: 123" for the first quiz?

If the embedded test run output is also hard to change, maybe just paste a few lines of correct output in the description for each quiz.

For example, for the first quiz (this one's tricky because there isn't much to print in a quiz that just asks you initialize variables):
"Your test output should show that the probability of bel_x is 0 for each point, e.g.:
bel_x=7:	0.00000	ground truth:	0.00000"

Or for the second quiz (which I'd want to see combined with the first):

"Your output should show a non-zero belief near landmarks, and a zero belief in the cells far from landmarks, e.g.:
bel_x=7:	0.00000	ground truth:	0.00000	
bel_x=8:	0.05556	ground truth:	0.00001"

**Comment by baumanab** [comment] 2017-10-23 04:36
This is great feedback.  Thank you!

**Comment by baumanab** [comment] 2017-10-25 19:26
I'm still working on other items, but we now have a more detailed explanation of the Motion model coding (Coding quiz II).  Please take a look and let us know what you think.

**Comment by CodingCanuck** [comment] 2017-10-26 03:47
I think the new instructions are an improvement, thanks!

The first quiz still says this (emphasis mine): 
"In the map above our initial believe state is illustrated, you will need to create this same initial believe state in your code. Complete the goal for each quiz by completing the quiz subtasks, labeled as TODO. **For comparison the final expected believe state is displayed to the right after you hit TEST RUN and labeled ground truth, your final results should match these exactly.**" Could we maybe just remove this bit from quizzes 1 and 2, and maybe mention that the ground truth output should match the output of the third quiz?

**Comment by baumanab** [comment] 2017-10-26 04:20
That is an excellent suggestion, yes, that can be done.

**Comment by baumanab** [comment] 2017-11-12 04:35
I wanted to touch base on this.  We have been actively working on the quiz code and other elements of Markov Localization.  I'm not certain when we will roll out the new material, but we haven't forgotten about this.

**Comment by baumanab** [comment] 2017-12-03 03:38
@CodingCanuck 

Hi, thanks again for your very helpful feedback on this lesson.  We have done the following:

- added concept quizzes
- refactored the coding quizzes
- removed the previous coding quizzes

Once we have received internal and external feedback we plan to make modifications and then add video content to accompany some of the quizzes.  We would really appreciate it if you could make some time to review the updated content and give feedback.

**Comment by baumanab** [comment] 2017-12-03 03:42
Closing this out since the grader issue has been addressed.  We can open other issues for whatever comes up in feedback.

**Closed by baumanab** 2017-12-03 03:42 UTC
Labels: code, enhancement, in progress, term_2

**Comment by CodingCanuck** [comment] 2018-01-07 17:47
Going through this again, this new version of the Motion Model section of term 2 lesson 11 Markov Localization is much better, and specifically the grading behavior is much more intuitive. Thanks so much for improving this!

Minor nits in 2.11.23 Determine Probabilities:
1) The page references `norm_pdf` five times, and a comment in the code references `norm_pdf` once: these should be `normpdf` to match the code.

Minor nits in 2.11.25 Motion Model Probability II:
1) The Transition Probability quiz is a bit confusing: it references `norm_pdf` but doesn't say how/where to use it: I jumped back to the implementation in the prior lesson 2.11.23 before realizing that there was a fresh implementation at the bottom of the page. The implementation bellow on 2.11.25 is mentioned in the quiz grader, but not in the actual quiz instructions: maybe update the quiz instructions to say:
"Use `normpdf` (see implementation at the bottom of the page) to determine..."

2) The page references `norm_pdf` three times: this should be `normpdf` to match the code.

3) For the Reference Equations at the bottom of the page, the transition model equation is bulleted: it should probably not be bulleted to match the other 2 equations.

Minor nits in 2.11.26 Coding the Motion Model:

1) The instructions say "prints the results to standout": should "standout" be `stdout` or "standard output"? I've never heard the term standout used in this context before.

2) The default/empty implementation of motion_model has an extra closing curly brace, which doesn't compile:
```
float motion_model(float pseudo_position, float movement, std::vector<float> priors,
                   int map_size, int control_stdev) {

    //initialize probability
    float position_prob = 0.0f;
    
    //YOUR CODE HERE

    }  <----- this brace should be removed
    return position_prob;
}
```

**Comment by CodingCanuck** [comment] 2018-01-07 17:48
Oops I see that you wanted me to open up new issues for feedback, I'll paste the above into a new issue

**Comment by CodingCanuck** [comment] 2018-01-07 17:50
Filed https://github.com/udacity/sdc-issue-reports/issues/1275 for the minor followups
