### ISSUE TITLE
T2.L11.S06 vague description, missing data

### ISSUE THREAD

**Issue by babo** [udacity/sdc-issue-reports#759] opened 2017-04-29 22:33 UTC
In term2, lesson 11 (Markov localization), section 6 the problem statement is vague. The expected code should print observations but there are no observations at the test dataset. Any code which compiles pass the filter. I expect some observation value to test, a better description of the expected output, and a downloadable sample to try locally. Please note, the task asks to print the first four values while the solution prints all.

**Comment by baumanab** [comment] 2017-07-25 06:27
Thank you for the feedback.  We are looking into this.  This may be a possible duplicate of #778, 781, and #879

**Comment by baumanab** [comment] 2017-08-23 06:43
The data package for running this code locally is now available for download in the resources tab.

**Comment by baumanab** [comment] 2017-09-26 18:19
Thanks again for the feedback.  This coding exercise has now been broken into 3 parts.  An explanation has been added that the quizzes are self-graded, with one solution offered to students at each step.  The lack of observations has also been explained and clarified.

**Closed by baumanab** 2017-09-26 18:19 UTC
Labels: code, data_request, duplicate, effort-Medium, enhancement, term_2

**Comment by asimay** [comment] 2017-10-01 12:20
+1, yes , you must set the observation file to 02, 03, or 04 by hand, these files have observation value.
