### ISSUE TITLE
Behavioral Cloning: More Networks raises error

### ISSUE THREAD

**Issue by HenryDev** [udacity/sdc-issue-reports#495] opened 2017-03-04 02:42 UTC
I'm following the code shown in the video in "More Networks" section:

```
    network = Sequential()
    network.add(Lambda(lambda pixel: pixel / 255 - 0.5, input_shape=(160, 320, 3)))
    network.add(convolutional.Convolution2D(6, 5, 5, activation='relu'))
    network.add(pooling.MaxPooling2D)
    network.add(convolutional.Convolution2D(6, 5, 5, activation='relu'))
    network.add(pooling.MaxPooling2D)
    network.add(Flatten())
    network.add(Dense(120))
    network.add(Dense(84))
    network.add(Dense(1))
```
and I'm getting an error on the line with the first Convolution2D layer:

> Negative dimension size caused by subtracting 5 from 3 for 'Conv2D' (op: 'Conv2D') with input shapes: [?,320,3,160], [5,5,160,6].

**Comment by pkpp1233** [comment] 2017-04-15 22:24
Figure this out?

**Comment by jntorres** [comment] 2017-06-06 04:24
i am also running into this issue

**Comment by baumanab** [comment] 2017-07-23 22:21
Duplicate of #521

**Comment by baumanab** [comment] 2017-12-15 05:17
Thank you for reporting this. It looks like this is an issue with the implementation rather than the grader. You have probably sorted this out by now but please reach out to mentors for help if it isn’t clear.

**Closed by baumanab** 2017-12-15 05:17 UTC
Labels: duplicate, effort-Medium, in progress, ready, term_1
