### ISSUE TITLE
Fix axis label to Finding Lane Lines 13. Hough Transform qizz 4/5

### ISSUE THREAD

**Issue by HaiShaw** [udacity/sdc-issue-reports#34] opened 2016-10-27 21:59 UTC
The axis labels of Image space to the right is the confusing, should be 'x' and 'y'.

**Comment by giladgressel** [comment] 2016-10-27 22:18
same as the issue I opened #33 but @HaiShaw is the one who spotted it 👍

**Comment by Brok-Bucholtz** [comment] 2016-10-28 06:27
@HaiShaw @giladgressel 

Closed this issues, since it's a duplicate of #33.

**Closed** 2016-10-28 20:44 UTC
