### ISSUE TITLE
Traffic Sign Project bug

### ISSUE THREAD

**Issue by sangxia** [udacity/sdc-issue-reports#612] opened 2017-03-25 09:19 UTC
Towards the end of the jupyter notebook, in the Activation Visualization section, in function outputFeatureMap, first line in the for loop: plt.subplot(6,8,featuremap+1). This breaks if the feature map has size larger than 48. I think changing the first one to ceil(featuremaps/8) would be a reasonable alternative.

**Comment by awbrown90** [comment] 2017-03-30 04:30
@sangxia thanks for the feedback I will look at experimenting with that.

**Comment by awbrown90** [comment] 2017-04-21 05:36
Hi @sangxia, finally had some time to look at that. I'm curious how did you have over 48 feature maps for one layer since the label size is only 32? I guess the layer would have to start long and then shorten. From the solution of using range(ceil(featuremaps/8)) is it actually a problem of the feature map not being divisible by 8? Just wanted to make sure I understand the problem, thanks.

**Comment by sangxia** [comment] 2017-04-21 09:55
I'm not sure how you get the number 32? In this paper http://people.idsia.ch/~juergen/nn2012traffic.pdf for example, there internal convolutional layers produce feature maps of size 100-250. You are right that I proposed using range(ceil(featuremaps/8)) because the feature map size is not necessarily divisible by 8.

**Comment by umer-rasheed** [comment] 2017-05-06 11:58
I used this code instead: 
https://medium.com/@awjuliani/visualizing-neural-network-layer-activation-tensorflow-tutorial-d45f8bf7bbc4

**Comment by umer-rasheed** [comment] 2017-05-06 12:09
The problem is with your function. 
plt.subplot(6,8,featuremap+1)
Change dimensions from 6 and 8 in the above line to the ones based on your convolutional layer depth. For example if your depth is 100, you can change it to plt.subplot(20,5,featuremap+1)

**Comment by sangxia** [comment] 2017-05-06 13:31
@umer-rasheed Yes, I can change it to `plt.subplot(20,5,featuremap+1)` as you suggested. The question is whether it is better to hardcode the number of rows and columns and remember to update it every time one changes the size of the feature, or to do it automatically.

In fact, the code in the medium post you linked to above (cell 7) does more or less what I was proposing.

**Comment by baumanab** [comment] 2017-08-06 06:38
Closing as it sounds like this is more of a difference in approach vs. a bug.  A discussion for working out the optimal approach is likely most appropriate and effective on the forums.

**Closed by baumanab** 2017-08-06 06:38 UTC
Labels: in progress
